apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  namespace: integration
spec:
  containers:
  - image: quay.io/ipedrazas/alpine:latest
    command: ["bash", "-c", "while true; do echo hello TEST; sleep 10; done"]
    imagePullPolicy: IfNotPresent
    name: curlcontainer
  restartPolicy: Always
