apiVersion: v1
kind: ReplicationController
metadata:
  name: siegetest
spec:
  replicas: 1
  selector:
    name: siegetest
    version: 1.0.0
  template:
    metadata:
      labels:
        name: siegetest
        version: 1.0.0
    spec:
      containers:
      - name: siegetest
        image: ipedrazas/siegetest:1.0.0
        ports:
        - containerPort: 8080
