apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - image: quay.io/ipedrazas/alpine:latest
    command:
      - bash
      - -c
      - "while true; do echo hello world; sleep 5; done"
    imagePullPolicy: IfNotPresent
    name: curlcontainer
  restartPolicy: Always


# kubectl exec curlpod -- nslookup nginxsvc
