apiVersion: v1
kind: Pod
metadata:
  name: singlepod
spec:
  containers:
  - image: ipedrazas/alpine:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curlcontainer
  restartPolicy: Always


# kubectl exec singlepod -- nslookup nginxsvc
