apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  containers:
  - image: ipedrazas/alpine:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curlcontainer
  restartPolicy: Always


# kubectl exec curlpod -- nslookup nginxsvc
