apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dockerfile
    env: ci
  name: dockerfile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dockerfile
        image.base: scratch
        lang: go
    spec:
      containers:
      - image: ipedrazas/dockerfile-validator:latest
        name: dockerfile
        ports:
        - name: dockerfile
          containerPort: 8080
