apiVersion: v1
kind: Service
metadata:
  name: pingsvcname
  labels:
    name: pingservice
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  selector:
    name: ping-update
