apiVersion: v1
kind: ReplicationController
metadata:
  name: ping-update-initial
spec:
  replicas: 1
  selector:
    name: ping-update
    version: 1.0.0
  template:
    metadata:
      labels:
        name: ping-update
        version: 1.0.0
    spec:
      containers:
      - name: ping-update
        image: ipedrazas/ping:1.0.0
        ports:
        - containerPort: 8080
