apiVersion: v1
kind: ReplicationController
metadata:
  name: pingrcname
  labels:
    name: pingrc
spec:
  replicas: 1
  selector:
    name: pingpodlabel
  template:
    metadata:
      labels:
        name: pingpodlabel
    spec:
      containers:
      - name: pingcontainer
        image: ipedrazas/ping:simple
        ports:
        - containerPort: 8080
